# Generated by Django 4.2.1 on 2023-07-12 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=255)),
                ('product_id', models.CharField(default='', max_length=255)),
                ('quantity', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=225)),
                ('quantity', models.CharField(default='', max_length=225)),
                ('Name', models.CharField(default='', max_length=225)),
                ('surname', models.CharField(default='', max_length=225)),
                ('telephone', models.CharField(default='', max_length=225)),
                ('email', models.CharField(default='', max_length=225)),
                ('city', models.CharField(default='', max_length=225)),
                ('address', models.CharField(default='', max_length=225)),
                ('comments', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('img', models.CharField(blank=True, max_length=250)),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField(blank=True)),
                ('screenSize', models.CharField(blank=True, max_length=250)),
                ('memoryCard', models.CharField(blank=True, max_length=250)),
                ('cpu', models.CharField(blank=True, max_length=250)),
                ('videoCard', models.CharField(blank=True, max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
