# Generated by Django 4.2.1 on 2023-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='orders',
            name='surname2',
            field=models.CharField(default='', max_length=225),
        ),
    ]
