# Generated by Django 4.2.1 on 2023-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_alter_orders_address_alter_orders_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='key',
            field=models.CharField(default='your_default_value', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
