# Generated by Django 4.2.1 on 2023-07-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_alter_orders_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='key',
        ),
    ]
