# Generated by Django 4.2.1 on 2023-07-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_remove_orders_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
