# Generated by Django 4.2.1 on 2023-07-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_alter_basket_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
