# Generated by Django 4.2.1 on 2023-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_orders_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_mts', models.CharField(max_length=225)),
                ('telephone_A1', models.CharField(max_length=225)),
                ('viber', models.CharField(max_length=225)),
                ('whatsApp', models.CharField(max_length=225)),
                ('telegram', models.CharField(max_length=225)),
                ('mail', models.CharField(max_length=225)),
                ('firm', models.CharField(max_length=225)),
                ('schedule', models.CharField(max_length=225)),
            ],
        ),
    ]
