# Generated by Django 4.2.1 on 2023-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0014_delivery_design_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='skype',
            field=models.CharField(default='', max_length=225),
        ),
    ]
