# Generated by Django 4.2.1 on 2023-08-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_contacts_skype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='firm',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='mail',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='telephone_A1',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='telephone_mts',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='viber',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='whatsApp',
        ),
    ]
