# Generated by Django 4.2.1 on 2023-08-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0016_rename_firm_contacts_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contacts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='design',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='information',
            field=models.TextField(),
        ),
    ]
