# Generated by Django 4.2.1 on 2023-08-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_alter_contacts_contacts_alter_delivery_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRegDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(max_length=225)),
                ('header2', models.CharField(max_length=225)),
                ('span', models.CharField(max_length=225)),
                ('information', models.TextField()),
            ],
        ),
    ]
