# Generated by Django 4.2.1 on 2023-09-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_pageregdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=225)),
                ('icons', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
            ],
        ),
    ]
