# Generated by Django 4.2.1 on 2023-09-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0019_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='idProduct',
        ),
    ]
