# Generated by Django 3.1.2 on 2024-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0022_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.RemoveField(
            model_name='newkey',
            name='user',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='PageRegDescription',
        ),
        migrations.DeleteModel(
            name='ProductName',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='material',
            name='author',
        ),
        migrations.RemoveField(
            model_name='material',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='material',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='material',
            name='created',
        ),
        migrations.RemoveField(
            model_name='material',
            name='img',
        ),
        migrations.RemoveField(
            model_name='material',
            name='memoryCard',
        ),
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
        migrations.RemoveField(
            model_name='material',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='material',
            name='screenSize',
        ),
        migrations.RemoveField(
            model_name='material',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='material',
            name='videoCard',
        ),
        migrations.AddField(
            model_name='material',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='material',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='NewKey',
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
